### PR TITLE
unit-tests for zero-rows-returned situations

### PR DESCRIPTION
**Pull request by gabor**
(part of https://github.com/grafana/sqlds/issues/118)

i wanted to add unit-tests that describe the current situation, i'll create a separate PR next that does the change.

NOTE: i had to do a small refactor of the code, because i don't know how to mock `sqlutil.FrameFromRows`. if anyone has a better idea, i'm all ears.

### CODE REVIEW

**Comment by scottlepp** [comment]
@gabor do you have to mock FrameFromRows?

**Comment by scottlepp** [comment]
@gabor try https://github.com/grafana/sqlds/blob/main/mock/sqlmock.go#L51

**Comment by gabor** [comment]
@scottlepp thanks for the info 👍 , i updated teh PR to use the mentioned test framework.

**Review by scottlepp — APPROVED** [review]

**Comment by gabor** [comment]
sorry @scottlepp , could you re-review it pls? i added one more commit, to cover all possible `format`s.

**Review by scottlepp — APPROVED** [review]

**Pull request merged**
